version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - LOGIN_COMMAND=$(aws sts assume-role --role-arn arn:aws:iam::140739330479:role/service-role/CodeBuildBasePolicy-workout-app-build-prod-us-east-2 --role-session-name CodeBuild-session | aws ecr get-login-password --debug --region $AWS_DEFAULT_REGION --username AWS --password-stdin)
      - eval $LOGIN_COMMAND
      - docker login -u AWS -p $LOGIN_COMMAND $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
