FROM --platform=linux/amd64 node:16-alpine

# Create app directory
WORKDIR /app

# Copy files to image
COPY . .

# Remove local node_modules
# RUN rm -rf ./client/node_modules
# RUN rm -rf ./server/node_modules
# RUN rm -rf ./node_modules

# Install ./ dependencies
RUN npm install

# Install ./server dependencies
RUN npm run install-server

EXPOSE 8080

CMD [ "npm", "run", "watch" ]